[versions]
# build
appVersionCode = "10"
appVersionName = "1.3.0"
agp = "8.11.1"
bcpkixJdk18on = "1.81"
compileSdk = "36"
core = "1.5.0"
extensionsXr = "1.0.0"
leakcanaryAndroid = "2.14"
minSdk = "26"
javaVersion = "17"
jvmTarget = "17"
wearMinSdk = "36"

#dependencies
accompanist = "0.37.3"
activityCompose = "1.10.1"
adaptive = "1.1.0"
animationAndroid = "1.8.3"
apksig = "9.0.0-alpha02"
appcompat = "1.7.1"
baselineprofile = "1.4.0"
benchmarkMacroJunit4 = "1.4.0"
camerax = "1.5.0-beta02"
coilCompose = "3.3.0"
coilGif = "3.3.0"
composeBom = "2025.08.00"
concurrent = "1.2.0"
converterGson = "2.11.0"
coreKtx = "1.16.0"
coreSplashscreen = "1.0.1"
crashlytics = "3.0.4"
datastore = "1.1.7"
espressoCore = "3.6.1"
firebaseBom = "34.2.0"
googleServices = "4.4.3"
googleOss = "17.2.0"
googleOssPlugin = "0.10.6"
guava = "33.4.8-android"
hiltAndroid = "2.56.2"
hiltLifecycleViewmodel = "1.0.0-alpha03"
hiltNavigationCompose = "1.2.0"
horologist = "0.7.15"
junit = "4.13.2"
junitVersion = "1.3.0"
kotlin = "2.2.0"
ksp = "2.2.0-2.0.2"
kotlinxCoroutines = "1.10.2"
kotlinxSerialization = "2.2.0"
kotlinxSerializationJson = "1.9.0"
kotlinxSerializationProtobuf = "1.8.1"
ktlint = "1.5.0"
lifecycleRuntimeKtx = "2.9.1"
lifecycleViewmodelNavigation3 = "1.0.0-alpha03"
loggingInterceptor = "5.1.0"
material = "1.12.0"
media3 = "1.7.1"
navigation3 = "1.0.0-alpha05"
okhttp = "4.12.0"
playServicesWearable = "19.0.0"
playServicesBaseTesting = "16.1.0"
poseDetection = "18.0.0-beta5"
profileinstaller = "1.4.1"
retrofit = "2.11.0"
robolectric = "4.14.1"
spotless = "7.0.2"
startup = "1.2.0"
runner = "1.6.2"
uiTextGoogleFonts = "1.8.3"
uiautomator = "2.4.0-alpha05"
uiTooling = "1.8.3"
validatorPush = "1.0.0-alpha08"
watchFacePush = "1.0.0-alpha01"
wear = "1.3.0"
wearCompose = "1.5.0"
wearComposeTooling = "1.4.1"
wearRemoteInteractions = "1.1.0"
window = "1.4.0"
aiEdge = "0.0.1-exp02"
lifecycleProcess = "2.9.1"
mlkitCommon = "18.11.0"
mlkitSegmentation = "16.0.0-beta1"
playServicesBase = "18.7.2"
timber = "5.0.1"
workRuntimeKtx = "2.10.4"
xr-compose = "1.0.0-alpha06"

[libraries]
accompanist-permissions = { module = "com.google.accompanist:accompanist-permissions", version.ref = "accompanist" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-adaptive = { module = "androidx.compose.material3.adaptive:adaptive", version.ref = "adaptive" }
androidx-adaptive-layout = { module = "androidx.compose.material3.adaptive:adaptive-layout", version.ref = "adaptive" }
androidx-adaptive-navigation = { module = "androidx.compose.material3.adaptive:adaptive-navigation", version.ref = "adaptive" }
androidx-animation-android = { group = "androidx.compose.animation", name = "animation-android", version.ref = "animationAndroid" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-app-startup = { group = "androidx.startup", name = "startup-runtime", version.ref = "startup" }
androidx-camera-camera2 = { module = "androidx.camera:camera-camera2", version.ref = "camerax" }
androidx-camera-compose = { module = "androidx.camera:camera-compose", version.ref = "camerax" }
androidx-camera-core = { module = "androidx.camera:camera-core", version.ref = "camerax" }
androidx-camera-lifecycle = { group = "androidx.camera", name = "camera-lifecycle", version.ref = "camerax" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom-alpha", version.ref = "composeBom" }
androidx-concurrent-futures-ktx = { module = "androidx.concurrent:concurrent-futures-ktx", version.ref = "concurrent" }
androidx-core = { module = "androidx.test:core", version.ref = "core" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "coreSplashscreen" }
androidx-datastore = { module = "androidx.datastore:datastore", version.ref = "datastore" }
androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastore" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "hiltNavigationCompose" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-lifecycle-viewmodel-navigation3 = { module = "androidx.lifecycle:lifecycle-viewmodel-navigation3", version.ref = "lifecycleViewmodelNavigation3" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-media3-exoplayer = { group = "androidx.media3", name = "media3-exoplayer", version.ref = "media3" }
androidx-media3-ui = { group = "androidx.media3", name = "media3-ui", version.ref = "media3" }
androidx-media3-ui-compose = { group = "androidx.media3", name = "media3-ui-compose", version.ref = "media3" }
androidx-navigation3-runtime = { module = "androidx.navigation3:navigation3-runtime", version.ref = "navigation3" }
androidx-navigation3-ui = { module = "androidx.navigation3:navigation3-ui", version.ref = "navigation3" }
androidx-runner = { group = "androidx.test", name = "runner", version.ref = "runner" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-text-google-fonts = { module = "androidx.compose.ui:ui-text-google-fonts", version.ref = "uiTextGoogleFonts" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-wear = { module = "androidx.wear:wear", version.ref = "wear" }
androidx-wear-compose-material = { group = "androidx.wear.compose", name = "compose-material3", version.ref = "wearCompose" }
androidx-wear-compose-foundation = { group = "androidx.wear.compose", name = "compose-foundation", version.ref = "wearCompose" }
androidx-wear-compose-ui-tooling = { group = "androidx.wear.compose", name = "compose-ui-tooling", version.ref = "wearComposeTooling" }
androidx-wear-remote-interactions = { module = "androidx.wear:wear-remote-interactions", version.ref = "wearRemoteInteractions" }
androidx-window = { module = "androidx.window:window", version.ref = "window" }
androidx-window-core = { module = "androidx.window:window-core", version.ref = "window" }
androidx-work-runtime-ktx = { module = "androidx.work:work-runtime-ktx", version.ref = "workRuntimeKtx" }
apksig = { module = "com.android.tools.build:apksig", version.ref = "apksig" }
bcpkix-jdk18on = { module = "org.bouncycastle:bcpkix-jdk18on", version.ref = "bcpkixJdk18on" }
coil-compose = { group = "io.coil-kt.coil3", name = "coil-compose", version.ref = "coilCompose" }
coil-compose-http = { group = "io.coil-kt.coil3", name = "coil-network-okhttp", version.ref = "coilCompose" }
coil-gif = { module = "io.coil-kt.coil3:coil-gif", version.ref = "coilGif" }
converter-gson = { group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "converterGson" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics" }
firebase-app-check = { module = "com.google.firebase:firebase-appcheck-playintegrity" }
firebase-appcheck-debug = { module = "com.google.firebase:firebase-appcheck-debug" }
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom" }
firebase-config = { module = "com.google.firebase:firebase-config" }
firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics" }
firebase-ai = { module = "com.google.firebase:firebase-ai" }
guava = { module = "com.google.guava:guava", version.ref = "guava" }
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hiltAndroid" }
hilt-android-testing = { group = "com.google.dagger", name = "hilt-android-testing", version.ref = "hiltAndroid" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "hiltAndroid" }
horologist-compose-layout = { module = "com.google.android.horologist:horologist-compose-layout", version.ref = "horologist" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
kotlinx-coroutines-play-services = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-play-services", version.ref = "kotlinxCoroutines"}
kotlinx-coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "kotlinxCoroutines" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
kotlinx-serialization-protobuf = { module = "org.jetbrains.kotlinx:kotlinx-serialization-protobuf", version.ref = "kotlinxSerializationProtobuf" }
leakcanary-android = { module = "com.squareup.leakcanary:leakcanary-android", version.ref = "leakcanaryAndroid" }
logging-interceptor = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "loggingInterceptor" }
mlkit-common = { group = "com.google.mlkit", name = "common", version.ref = "mlkitCommon" }
mlkit-pose-detection = { module = "com.google.mlkit:pose-detection", version.ref = "poseDetection" }
mlkit-segmentation = { module = "com.google.android.gms:play-services-mlkit-subject-segmentation", version.ref = "mlkitSegmentation" }
okhttp = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp" }
play-services-wearable = { module = "com.google.android.gms:play-services-wearable", version.ref = "playServicesWearable" }
play-services-base-testing = { module = "com.google.android.gms:play-services-base-testing", version.ref = "playServicesBaseTesting" }
retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
retrofit-kotlin-serialization = { group = "com.squareup.retrofit2", name = "converter-kotlinx-serialization", version.ref = "retrofit" }
robolectric = { group = "org.robolectric", name = "robolectric", version.ref = "robolectric" }
ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling", version.ref = "uiTooling" }
androidx-uiautomator = { group = "androidx.test.uiautomator", name = "uiautomator", version.ref = "uiautomator" }
androidx-benchmark-macro-junit4 = { group = "androidx.benchmark", name = "benchmark-macro-junit4", version.ref = "benchmarkMacroJunit4" }
androidx-profileinstaller = { group = "androidx.profileinstaller", name = "profileinstaller", version.ref = "profileinstaller" }
ai-edge = { group = "com.google.ai.edge.aicore", name = "aicore", version.ref = "aiEdge" }
google-oss-licenses = { group = "com.google.android.gms", name = "play-services-oss-licenses", version.ref = "googleOss" }
google-oss-licenses-plugin = { group = "com.google.android.gms", name = "oss-licenses-plugin", version.ref = "googleOssPlugin" }
androidx-lifecycle-process = { group = "androidx.lifecycle", name = "lifecycle-process", version.ref = "lifecycleProcess" }
validator-push-android = { module = "com.google.android.wearable.watchface.validator:validator-push-android", version.ref = "validatorPush" }
validator-push-cli = { module = "com.google.android.wearable.watchface.validator:validator-push-cli", version.ref = "validatorPush" }
watchface-push = { group = "androidx.wear.watchfacepush", name="watchfacepush", version.ref = "watchFacePush" }
play-services-base = { group = "com.google.android.gms", name = "play-services-base", version.ref = "playServicesBase" }
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }
google-firebase-appcheck-debug = { group = "com.google.firebase", name = "firebase-appcheck-debug"}
androidx-xr-compose = { group = "androidx.xr.compose", name="compose", version.ref = "xr-compose"}
androidx-xr-extensions = { module = "com.android.extensions.xr:extensions-xr", version.ref = "extensionsXr" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "crashlytics" }
google-services = { id = "com.google.gms.google-services", version.ref = "googleServices" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hiltAndroid" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-ksp = { id ="com.google.devtools.ksp", version.ref = "ksp" }
serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlinxSerialization" }
android-test = { id = "com.android.test", version.ref = "agp" }
baselineprofile = { id = "androidx.baselineprofile", version.ref = "baselineprofile" }
composeScreenshot = { id = "com.android.compose.screenshot", version = "0.0.1-alpha10" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
